# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: hyrulecoder
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: langchainbook-chatgptslackfunction
service: LangChainBook-ChatGPTSlackFunction

provider:
  name: aws
  region: ap-northeast-1
  stage: dev
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource: '*'

package:
  patterns:
    - '!.venv/**'
    - '!ENV'
    - '!node_modules'
    - '!.env'
    - '!.env.template'
    - '!.gitignore'
    - '!.python-version'
    - '!.git/**'

functions:
  app:
    name: LangChainBook-ChatGPTSlackFunction-${sls:stage}-app
    handler: app.handler
    runtime: python3.10
    memorySize: 512
    timeout: 900
    url: true

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin